### ISSUE TITLE
Always got invalid_client from Apple

### ISSUE THREAD

**Issue by laurocesar** [klausbetz/apple-identity-provider-keycloak#18]
I'm using version 1.3.0 and Keycloak 20.0.1 configured as follows:

<img width="991" alt="image" src="https://user-images.githubusercontent.com/297989/204773442-0e447e56-6723-4c16-a1bf-85c79570d26c.png">

- Service ID: From "Certificates, Identifiers & Profiles", "Edit your Services ID Configuration", "Identifier" field
- Team ID: the 10 digits number on upper right side, under the username
- Key ID: "Certificates, Identifiers & Profiles", "View Key Details", "Key ID" field. I have selected "Sign In with Apple" checkbox and configured to a group Id
- p8Key: `.p8` file's content as a single line: "-----BEGIN PRIVATE KEY-----M....C-----END PRIVATE KEY-----"

<img width="1135" alt="image" src="https://user-images.githubusercontent.com/297989/204774624-f4802d86-8f05-4873-a758-f7dc2633f63c.png">

But I always got this:

> invalid_client
> Invalid client.

<img width="262" alt="image" src="https://user-images.githubusercontent.com/297989/204773592-bf72e765-3962-4963-9ec8-e89c04912de3.png">

**Comment by klausbetz** [comment]
Hi @laurocesar,  
thx for reaching out to me.

Since I don't get this error anymore, I assume there's some kind of misconfiguration going on.

Apple likes to reuse error messages for different kinds of errors. And I think that's the case here.

`invalid_client` can mean two things if I remember correctly:
- `client_id` (Service ID) doesn't match the one that is configured in your Apple Developer account
- `Redirect URI` is not configured or doesn't match the ones configured in your Service in your Apple Developer account

Maybe this guide form okta helps you with configuring the Service in your Apple Developer account.  
Besides that, I'll create a wiki on how to configure a service correctly.

In case you managed to fix it on your side, please let me know what was causing the error.

**Comment by laurocesar** [comment]
In fact, @klausbetz , there was nothing wrong. We waited just one day and magically it was working!

As suggestion, in this tip you should write:

> Raw content of Apple's p8 key file (example:  "-----BEGIN PRIVATE KEY-----!CONTENT!-----END PRIVATE KEY-----")

<img width="327" alt="image" src="https://user-images.githubusercontent.com/297989/205606319-e6445935-3466-40d6-8b36-f24f9840b453.png">
