### ISSUE TITLE
Check setting status

### ISSUE THREAD

**Issue by giabao1008** [klausbetz/apple-identity-provider-keycloak#25]
Hi, i setup login ios with this lib, but when i tried login with postman, it show me error :

`{
    "error": "invalid_token",
    "error_description": "invalid token"
}`
How can i check if i set up correctly ?

Note: i ve setted up login with google and facebook, they work successfully
When loggin with apple, i tried with both ID token and authorization code

**Comment by giabao1008** [comment]
im using keycloak v20.0.0

**Comment by giabao1008** [comment]
i've added my url to redirect urls in apple: https://my-domain-url/realms/my-realm/broker/apple/endpoint

**Comment by klausbetz** [comment]
This is actually a pretty tough one.

Since Apple doesn't provide any API or tools or anything else to test the configuration, it's just the sad truth that hits us here.  
At least now it's not possible to automatically validate the configuration values.

When configuring Sign-in-with-Apple, it's usually a bit of trial and error until you succeed.  
However, there are really good guides out there, that assist you configuring SIWA (like this [one](https://developer.okta.com/blog/2019/06/04/what-the-heck-is-sign-in-with-apple)).
