### ISSUE TITLE
Keycloak 18.0.2 with 1.2.0 provider does not pickup user name and password from APPLE

### ISSUE THREAD

**Issue by UrosCvijan** [klausbetz/apple-identity-provider-keycloak#41]
Hello, 

Awesome provider, thank you very much. 

We have some issues, Apple is requesting that we don't show update Username and Lastname on first login/sign up, and that those should be filled from Apple. But in the first-broker-login we have put the missing option, so that dialog will open only if provider does not pick up username/lastname from the IDP. So I guess this is the case here. We left out defaultScope, we put name%20lastname, and still on first login/sigup we get the popup to update user information. 

Are we missing something here? Is it our version of keyclaok and provider that is causing this, or can we do something to pick up the Name/LastName from Apple and for those to be automatically filled in? 

All the best, 
Uros

**Comment by klausbetz** [comment]
Hi @UrosCvijan,

Please try using `name%20email`.

Note that Apple sends firstname and lastname only at the first login.  
In order to test the login with the same user over and over again, you can unlink your Application from your user's SIWA here: https://appleid.apple.com
Then Apple sends firstname and lastname again.

**Comment by UrosCvijan** [comment]
Hey @klausbetz 
Thank you very much, after I removed the Application from SIWA it worked. 
Keep up the awesome work :) 
I will close the issue
