### ISSUE TITLE
Problem with users using Hide My Email

### ISSUE THREAD

**Issue by tungboom** [klausbetz/apple-identity-provider-keycloak#58]
Hi,
When I hide Email and sign in with Apple, new account created in keycloak with email: jnj78bq6xe@privaterelay.appleid.com.
How to get the user's real email? Or is there a way to force users to enter their real email when signing in with Apple?

**Comment by klausbetz** [comment]
Hi @tungboom,
Unfortunately, there's no way to get the real email address of the user.  
The user decides upon registration whether he wants to share a hidden or his real email address.

I guess, as long as Apple cares about privacy of users, they won't change this behavior.

At least from a developer point of view, there's nothing you can do. It's about the user that signs in to your app.

**Comment by 123dev** [comment]
It would be nice to have a way to reject a private email during sign-up / sign-in and not register the app with Apple if a private email is used.
Otherwise, even if one sets up a workflow to not accept or force changing the email within Keycloak, the registered app is still present on the Apple side, and one has to instruct the user to go a delete the app and reregister without hiding the email.

By the way, is it possible to set a name for the registered app?
Current it says `Keycloak App`

**Comment by klausbetz** [comment]
Hi @123dev,

It's still not possible to force users to share their real email address.  

Usually, the name of the app is set in your Apple Developer account. Try renaming your App ID.

**Comment by 123dev** [comment]
> Hi [@123dev](https://github.com/123dev),
> 
> It's still not possible to force users to share their real email address.
> 
> Usually, the name of the app is set in your Apple Developer account. Try renaming your App ID.

Thanks for the quick reply.
No I don't want to force users, they have a choice, if they choose to hide the email, I don't want to register the app and just display an appropriate  message about their choice, at that point they can re-enter the the sign-up sign-in and share their email, or just leave.
However if the app is registered with private email, the only way they can do that is to go into their account and unregister the app, 

What I'm asking for is that, if the email is set to private, have an option in the plugin to not register the app and display a message.

I'll check renaming the App ID in Apple Developer account. 
Thanks
